export const articleSources = [
  {"id": "editorial-36ef8df20e6958", "title": "FDA’s food-allergy guidance", "organization": "www.fda.gov", "url": "https://www.fda.gov/food/buy-store-serve-safe-food/food-allergies-what-you-need-know"},
  {"id": "editorial-cb248e4d525549", "title": "USDA guidance", "organization": "ask.fsis.usda.gov", "url": "https://ask.fsis.usda.gov/article/How-do-I-keep-foods-safe-at-a-buffet"},
  {"id": "editorial-24eedf91c1e80b", "title": "USDA’s air-fryer food-safety guidance", "organization": "www.fsis.usda.gov", "url": "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/air-fryers-and-food-safety"},
  {"id": "editorial-707d348a93cfe6", "title": "safe temperature guidance", "organization": "www.fsis.usda.gov", "url": "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/safe-temperature-chart"},
  {"id": "editorial-72966014b409cd", "title": "USDA’s advice against washing raw chicken", "organization": "ask.fsis.usda.gov", "url": "https://ask.fsis.usda.gov/article/Should-I-wash-chicken-or-other-poultry-before-cooking"},
  {"id": "editorial-577c547e55d8ef", "title": "FDA's safe food handling guidance", "organization": "www.fda.gov", "url": "https://www.fda.gov/consumers/womens-health-topics/food-safety-home"},
  {"id": "editorial-2de40787a85f3c", "title": "FDA's safe food handling guidance", "organization": "www.fda.gov", "url": "https://www.fda.gov/consumers/consumer-updates/food-safety-home"},
  {"id": "editorial-8bba42f980e442", "title": "Poison Control first-aid instructions", "organization": "www.poison.org", "url": "https://www.poison.org/first-aid-for-poisonings"},
  {"id": "editorial-54d8a8754bc67d", "title": "CDC infant feeding guidance", "organization": "www.cdc.gov", "url": "https://www.cdc.gov/infant-toddler-nutrition/foods-and-drinks/foods-and-drinks-to-avoid-or-limit.html"},
  {"id": "editorial-0d2fe59cd0b38f", "title": "USDA explanation of the two-hour rule", "organization": "ask.fsis.usda.gov", "url": "https://ask.fsis.usda.gov/article/What-is-the-2-Hour-Rule-with-leaving-food-out"},
  {"id": "editorial-237bcc88b71fd7", "title": "USDA food-safety basics", "organization": "www.fsis.usda.gov", "url": "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics"},
  {"id": "editorial-deae295be6a004", "title": "FDA food-allergy guidance", "organization": "www.fda.gov", "url": "https://www.fda.gov/food/food-labeling-nutrition/food-allergies"},
  {"id": "editorial-a0a6ec0a9ca140", "title": "FoodSafety.gov four-step guidance", "organization": "www.foodsafety.gov", "url": "https://www.foodsafety.gov/keep-food-safe/4-steps-to-food-safety"},
  {"id": "editorial-645eb18630e65b", "title": "FDA's food allergy information", "organization": "www.fda.gov", "url": "https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/food-allergies"},
  {"id": "editorial-9da7830d173e02", "title": "Capsaicin exposure guidance", "organization": "www.poison.org", "url": "https://www.poison.org/articles/capsaicin-when-the-chili-is-too-hot"},
  {
    id: "poison-control-capsaicin",
    title: "Is the One Chip Challenge Dangerous?",
    organization: "Poison Control",
    url: "https://www.poison.org/articles/is-the-one-chip-challenge-dangerous",
  },
  {
    id: "nationwide-one-chip",
    title: "The One Chip Challenge: Too Hot to Handle",
    organization: "Nationwide Children's Hospital",
    url: "https://www.nationwidechildrens.org/family-resources-education/700childrens/2023/09/the-one-chip-challenge",
  },
  {
    id: "cdc-food-safety",
    title: "Preventing Food Poisoning",
    organization: "Centers for Disease Control and Prevention",
    url: "https://www.cdc.gov/food-safety/prevention/index.html",
  },
  {
    id: "foodsafety-four-steps",
    title: "4 Steps to Food Safety",
    organization: "FoodSafety.gov",
    url: "https://www.foodsafety.gov/keep-food-safe/4-steps-to-food-safety",
  },
  {
    id: "fda-food-allergies",
    title: "Food Allergies",
    organization: "U.S. Food and Drug Administration",
    url: "https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/food-allergies",
  },
  {
    id: "fsis-big-nine",
    title: "Food Allergies: The Big 9",
    organization: "USDA Food Safety and Inspection Service",
    url: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/food-allergies-big-9",
  },
  {
    id: "datassential-spicy",
    title: "Spicy Food Trends",
    organization: "Datassential",
    url: "https://datassential.com/resource/spicy-food-trends/",
  },
  {
    id: "imarc-hot-sauce",
    title: "Hot Sauce Market Report",
    organization: "IMARC Group",
    url: "https://www.imarcgroup.com/hot-sauce-market",
  },
  {
    id: "pepper-joe-scoville",
    title: "Pepper Heat Scale and Scoville Chart",
    organization: "Pepper Joe's",
    url: "https://pepperjoe.com/blogs/blog/hot-pepper-heat-scale-and-the-scoville-scale",
  },
  {
    id: "fda-sesame",
    title: "The FASTER Act: Sesame Is the Ninth Major Food Allergen",
    organization: "U.S. Food and Drug Administration",
    url: "https://www.fda.gov/food/food-allergies/faster-act-sesame-ninth-major-food-allergen",
  },
];
